name: I18N-Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  file_changes:
    name: Razorpay I18N Linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Get changed files
        id: changed-files
        run: |
            if ${{ github.event_name == 'pull_request' }}; then
                echo "changed_files=$(git diff --name-only --line-prefix=`git rev-parse --show-toplevel`/ -r HEAD^1 HEAD | xargs)" >> $GITHUB_OUTPUT
            else
                echo "changed_files=$(git diff --name-only --line-prefix=`git rev-parse --show-toplevel`/ ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT
            fi
      - name: Running-I18N-Linter
        id: text-files
        run: |
          checkKeywords() {
            local file="$1"
            local original_content=$(cat "$file")
            local content_diff=$(git diff origin/${{ github.event.pull_request.base.ref }} origin/${{ steps.extract_branch.outputs.branch }} -- "$file")
            local error_msg_list=(
              "Hardcoded currency {} found, please use currency from User model file something like- props.user.merchant.currency"
              "Region-specific keyword detected, please use generic terms as we also support multiple regions merchants who might not be aware of {} keyword"
              "Avoid hardcoding currency symbols instead import symbols from rzp-utils file"
            )
            local ignore_linter_directives=("ignore-i18n-linter" "ignore-i18n-linter-next-line" "ignore-i18n-linter-start" "ignore-i18n-linter-end")
            local warning_title="Razorpay/I18N-Linter"
            local file_content=()
            local currencies=("INR" "RM" "MYR" "USD")
            local currencySymbols=("\\₹")
            local regionSpecificWords=("RBI" "GST" "CIN" "Ruppees")

            while IFS= read -r line || [[ "$line" ]]; do
              file_content+=("$line")
            done < "$file"

            # Helper function to check if a line should be ignored
            shouldIgnoreWholeFile() {
              local regex="^\\s*((\\/\\/)|(\\/\\*))\\s*(${ignore_linter_directives[0]})"
              local is_first_line_matched=$(echo "${file_content[0]}" | grep -P "$regex")
              if [[ -n "$is_first_line_matched" ]]; then
                return 1
              fi
              return 0
            }

            linterIgnore() {
              local line_text=$1
              local ignore_text=$2
              local regex="^\\s*((\\/\\/)|(\\/\\*))\\s*($ignore_text)"
              local match_found=$(echo "$line_text" | grep -P "$regex")
              if [[ -n "$match_found" ]]; then
                echo 1
              else
                echo 0
              fi
            }

            hasMatch() {
              local regex="$1"
              local type="$2"
              local keyword="$3"
              local line_number="$4"
              local text_to_be_checked="$5"
              local match=$(echo "$text_to_be_checked" | grep -P "$regex")

              if [[ -n "$match" ]]; then
                local error_msg
                local warning_msg
                
                case "$type" in
                  "currency")
                      error_msg="${error_msg_list[0]}"
                      warning_title="Region specific currency detected"
                      ;;
                  "symbol")
                      error_msg="${error_msg_list[2]}"
                      warning_title="Region specific symbol detected"
                      ;;
                  "text")
                      error_msg="${error_msg_list[1]}"
                      warning_title="Region specific text detected"
                      ;;
                  *)
                      warning_msg="Region specific text detected, please take approval from i18n team for this change"
                      ;;
                esac
                warning_msg="${error_msg//\{\}/$keyword}"
                echo "::warning file=$file,line=$((line_number + 1)),col=15,title=$warning_title::$warning_msg"
              fi
            }

            if shouldIgnoreWholeFile; then
              echo "Linter now scanning code on file:$file"
              between_line_linter_ignore_flag=0
              next_line_linter_ignore_flag=0
              for ((i = 0; i < ${#file_content[@]}; i++)); do
                line_text="${file_content[i]}"
                next_line_linter_ignore=$(linterIgnore "$line_text" "${ignore_linter_directives[1]}")
                
                start_line_linter_ignore=$(linterIgnore "$line_text" "${ignore_linter_directives[2]}")

                end_line_linter_ignore=$(linterIgnore "$line_text" "${ignore_linter_directives[3]}")

                if [ $start_line_linter_ignore -eq 1 ]; then
                  echo "start line linter ignore comment detected"
                  between_line_linter_ignore_flag=1
                elif [[ $next_line_linter_ignore -eq 1 ]]; then
                  echo "next line linter ignore comment detected"
                  next_line_linter_ignore_flag=1
                elif [ $next_line_linter_ignore_flag -eq 1 ]; then
                  next_line_linter_ignore_flag=0
                elif [ $between_line_linter_ignore_flag -eq 1 ]; then
                  if [ $end_line_linter_ignore -eq 1]
                    echo "end line linter ignore comment detected"
                    between_line_linter_ignore_flag=0
                  fi
                else
                  local lineWithoutComments=$(echo "$line_text" | sed -E 's/\/\/.*|\/\*[^*]*\*\///g')
                  local words=()
                  local warning_msg
                  IFS=' ' read -r -a words <<< "$line_text"

                  for word in "${words[@]}"; do
                    for keyword in "${regionSpecificWords[@]}"; do
                      hasMatch "\\b(?<!\\.)$keyword\\b" "text" "$keyword" "$i" "$word"
                    done

                    for symbol in "${currencySymbols[@]}"; do
                      hasMatch "$symbol" "symbol" "$symbol" "$i" "$word"
                    done

                    for currency in "${currencies[@]}"; do
                      hasMatch "\\b(?<!\\.)$currency\\b" "currency" "$currency" "$i" "$word"
                    done
                  done
                fi
              done
            else
              echo "Whole file ignore comment found, aborting linter run on file: $file"
              printf "\n"
            fi
          }

          if [ "$steps.extract_branch.outputs.branch" != "revert-*" ] && [ "$steps.extract_branch.outputs.branch" != "skiplint-*" ]; then
            for file in ${{ steps.changed-files.outputs.changed_files }}; do
              if ! [[ "$file" =~ \.github.* || "$file" =~ __test__ ]]; then
                if [[ "$file" =~ \.(js|jsx|ts|tsx|html)$ ]]; then
                  checkKeywords "$file"
                else
                  echo "Unsupported file extension found, linter wont be running on file: $file"
                  printf "\n"
                fi
              else
                echo "File is a part of folder which have been flaged to be ignored, hence linter will ignore file: $file"
                printf "\n"
              fi
            done
          else
            echo "Restricted branch name found, linter won't run"
          fi

