name: I18N-Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  file_changes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Get changed files
        id: changed-files
        run: |
            if ${{ github.event_name == 'pull_request' }}; then
                echo "changed_files=$(git diff --name-only --line-prefix=`git rev-parse --show-toplevel`/ -r HEAD^1 HEAD | xargs)" >> $GITHUB_OUTPUT
            else
                echo "changed_files=$(git diff --name-only --line-prefix=`git rev-parse --show-toplevel`/ ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT
            fi
      - name: Running-I18N-Linter
        id: text-files
        run: |
              for file in ${{ steps.changed-files.outputs.changed_files }}; do
                validFile() {
                  getFileExtension() {
                    local pathName="$1"
                    echo "${pathName##*.}"
                  }
                  local pathName="$1"
                  local supportedFileExtension=("js" "jsx" "ts" "tsx" "html")
                  local excludeFolders=(".github" "__test__")
                  local excludedBranch=("revert" "hotfix")
                  local branchName="${{ steps.extract_branch.outputs.branch }}"
                  local fileExtension=$(getFileExtension "$pathName")
                  local isSupportedFileExtension=false
                  local isExcludedFolder=false

                  for ext in "${supportedFileExtension[@]}"; do
                    if [[ "$ext" == "$fileExtension" ]]; then
                      isSupportedFileExtension=true
                      break
                    fi
                  done

                  for folder in "${excludeFolders[@]}"; do
                    if [[ "$pathName" == *"$folder"* ]]; then
                      isExcludedFolder=true
                      break
                    fi
                  done

                  if [[ "$isSupportedFileExtension" == true && "$isExcludedFolder" == false ]]; then
                    return 0
                  fi

                  return 1
                }
                if validFile "$file"; then
                  original_content=$(cat "$file")
                  content_diff="$(git diff origin/${{ github.event.pull_request.base.ref }} origin/${{ steps.extract_branch.outputs.branch }} -- $file)"
                  checkKeywords() {
                    local code="${1}"
                    local currencies=("INR" "Ruppees" "RM" "MYR")
                    # local currencySymbols=("₹" "\\$-*(?!{)")
                    local currencySymbols=("₹" "\\$-\\*\\(\\?\\!\\{\\)")
                    # local currencySymbols=("RBI")
                    local regionSpecificWords=("RBI" "GST" "CIN")
                    local new_lines=()
                    local errors=()
                    
                    while IFS= read -r line || [[ "$line" ]]; do
                      new_lines+=("$line")
                    done < "$file"

                    for ((i = 0; i < ${#new_lines[@]}; i++)); do
                      local line="${new_lines[i]}"
                      local lineWithoutComments=$(echo "$line" | sed -E 's/\/\/.*|\/\*[^*]*\*\///g')
                      local words=()

                      IFS=' ' read -r -a words <<< "$lineWithoutComments"

                      for word in "${words[@]}"; do
                        hasMatch() {
                          local pattern="$1"
                          local type="$2"
                          local regex
                          regex="$pattern"
                          local match
                          match=$(echo "$word" | grep -oE "$regex")

                          if [[ -n "$match" ]]; then
                            local error_mapping
                            local error_msg

                            error_mapping["currency"]="Hard coded currency {} found, please use currency from User model file something like- props.user.merchant.currency"
                            error_mapping["symbol"]="Avoid hardcoding currency symbols instead import symbols from rzp-utils file"
                            error_mapping["text"]="Region specific keyword detected, please use genric term as we are also supporting multiple regions merchant who might be not aware of {} keyword"

                            if [[ "${error_mapping[$type]+exists}" ]]; then
                              error_msg="${error_mapping[$type]//\{\}/$word}"
                            else
                              error_msg="Region specific text detected, please take approval from i18n team for this change"
                            fi
                            echo "::warning file=$file,line=$((i + 1)),col=15::$error_msg"
                          fi
                        }

                        for keyword in "${regionSpecificWords[@]}"; do
                            hasMatch "\\b$keyword\\b" "text"
                        done

                        for symbol in "${currencySymbols[@]}"; do
                            hasMatch "$symbol" "symbol"
                        done

                        for currency in "${currencies[@]}"; do
                            hasMatch "\\b$currency\\b" "currency"
                        done
                      done
                    done

                    printf '%s\n' "${errors[@]}"
                  }
                  errors=$(checkKeywords "$original_content")
                  if [[ -n $errors ]]; then
                    while IFS= read -r error; do
                      echo "$error" >&2
                    done <<< "$errors"
                  else
                    echo "No hardcoding related to I18N found."
                  fi
                  echo "Valid file"
                else
                  echo "Linter won't run on this file"
                fi
              done