name: I18N-Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  file_changes:
    name: Razorpay I18N Linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Get changed files
        id: changed-files
        run: |
            if ${{ github.event_name == 'pull_request' }}; then
                echo "changed_files=$(git diff --name-only --line-prefix=`git rev-parse --show-toplevel`/ -r HEAD^1 HEAD | xargs)" >> $GITHUB_OUTPUT
            else
                echo "changed_files=$(git diff --name-only --line-prefix=`git rev-parse --show-toplevel`/ ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT
            fi
      - name: Running-I18N-Linter
        id: text-files
        run: |
          total_warnings_collected=0
          checkKeywords() {
            local file="$1"
            local warnings_found=0
            local original_content=$(cat "$file")
            local content_diff=$(git diff origin/${{ github.event.pull_request.base.ref }} origin/${{ steps.extract_branch.outputs.branch }} -- "$file")
            local error_msg_list=(
              "Currency value {} is hardcoded, consider using the currency from the User model file, such as props.user.merchant.currency."
              "Region-specific keyword detected, please use generic terms as we also support merchants from multiple regions who may not be familiar with the {} keyword"
              "Avoid direct currency symbol usage, import symbols from the rzp-utils file instead"
            )
            local ignore_linter_directives=("ignore-i18n-linter" "ignore-i18n-linter-next-line" "ignore-i18n-linter-start" "ignore-i18n-linter-end")
            local warning_title="Razorpay/I18N-Linter"
            local file_content=()
            local currencies=("INR" "RM" "MYR" "USD")
            local currency_symbols=("\\₹")
            local region_specific_words=("RBI" "GST" "CIN" "Ruppees")
            local linesToBeIgnored=("import")

            while IFS= read -r line || [[ "$line" ]]; do
              file_content+=("$line")
            done < "$file"

            checkAgainstRegex() {
              local line_text=$1
              local regex="$2"
              local match_found=$(echo "$line_text" | grep -P "$regex")
              if [[ -n "$match_found" ]]; then
                echo 1
              else
                echo 0
              fi
            }

            should_ignore_whole_file=$(checkAgainstRegex "${file_content[0]}" "^\\s*((\\/\\/)|(\\/\\*))\\s*(${ignore_linter_directives[0]})")
            if [ $should_ignore_whole_file -eq 0 ]; then
              printf "Linter now scanning code on file:$file \n"
              echo -e "\e[31mRed Text\e[0m \e[32mGreen Text\e[0m"
              between_line_linter_ignore_flag=0
              next_line_linter_ignore_flag=0
              for ((i = 0; i < ${#file_content[@]}; i++)); do
                line_text="${file_content[i]}"
                next_line_linter_ignore=$(checkAgainstRegex "$line_text" "^\\s*((\\/\\/)|(\\/\\*))\\s*(${ignore_linter_directives[1]})")
                start_line_linter_ignore=$(checkAgainstRegex "$line_text" "^\\s*((\\/\\/)|(\\/\\*))\\s*(${ignore_linter_directives[2]})")
                end_line_linter_ignore=$(checkAgainstRegex "$line_text" "^\\s*((\\/\\/)|(\\/\\*))\\s*(${ignore_linter_directives[3]})")
                lines_containing_specific_word_ignore=$()

                if [[ $start_line_linter_ignore -eq 1 ]]; then
                  printf "<------- start line linter ignore comment detected -----> \n"
                  printf "Following code will be skipped by linter \n"
                  between_line_linter_ignore_flag=1
                elif [[ $next_line_linter_ignore -eq 1 ]]; then
                  printf "<------- next line linter ignore comment detected -----> \n"
                  next_line_linter_ignore_flag=1
                elif [[ $next_line_linter_ignore_flag -eq 1 ]]; then
                  printf "$line_text \n"
                  next_line_linter_ignore_flag=0
                elif [[ $between_line_linter_ignore_flag -eq 1 ]]; then
                  if [[ $end_line_linter_ignore -eq 1 ]]; then
                    printf "<------- end line linter ignore comment detected -----> \n"
                    between_line_linter_ignore_flag=0
                  else
                    printf "$line_text \n"
                  fi
                else
                  local line_without_comments=$(echo "$line_text" | sed -E 's/\/\/.*|\/\*[^*]*\*\///g')
                  local should_line_be_ignored=0
                  for term in "${linesToBeIgnored[@]}"; do
                    local match_found=$(checkAgainstRegex "$line_without_comments" "\\b$term\\b")
                    if [ $match_found -eq 1 ]; then
                      should_line_be_ignored=1
                      break
                    fi
                  done
                  if [[ $should_line_be_ignored -eq 1 ]]; then
                    printf "Line contains restricted keyword, linter will exclude the line: $line_without_comments \n"
                  else
                    local words=()
                    local warning_msg
                    IFS=' ' read -r -a words <<< "$line_without_comments"

                    for word in "${words[@]}"; do
                      for keyword in "${region_specific_words[@]}"; do
                        match_found=$(checkAgainstRegex "$word" "\\b(?<!\\.)$keyword\\b")
                        if [ $match_found -eq 1 ]; then
                          error_msg="${error_msg_list[1]}"
                          warning_msg="${error_msg//\{\}/$keyword}"
                          echo "::warning file=$file,line=$((i + 1)),col=15,title="Region specific text detected"::$warning_msg"
                          warnings_found=$((warnings_found+1))
                        fi
                      done

                      for symbol in "${currency_symbols[@]}"; do
                        match_found=$(checkAgainstRegex "$word" "$symbol")
                        if [ $match_found -eq 1 ]; then
                          error_msg="${error_msg_list[2]}"
                          warning_msg="${error_msg//\{\}/$symbol}"
                          echo "::warning file=$file,line=$((i + 1)),col=15,title="Region specific symbol detected"::$warning_msg"
                          warnings_found=$((warnings_found+1))
                        fi
                      done

                      for currency in "${currencies[@]}"; do
                        match_found=$(checkAgainstRegex "$word" "\\b(?<!\\.)$currency\\b")
                        if [ $match_found -eq 1 ]; then
                          error_msg="${error_msg_list[0]}"
                          warning_msg="${error_msg//\{\}/$currency}"
                          echo "::warning file=$file,line=$((i + 1)),col=15,title="Region specific currency detected"::$warning_msg"
                          warnings_found=$((warnings_found+1))
                        fi
                      done
                    done
                  fi
                fi
              done
            else
              printf "Whole file ignore comment detected, linter will skip the file: $file \n"
            fi
            total_warnings_collected=$((warnings_found+total_warnings_collected))
            printf "$warnings_found Warnings identified for the file:$file \n\n"
          }

          if [ "$steps.extract_branch.outputs.branch" != "revert-*" ] && [ "$steps.extract_branch.outputs.branch" != "skiplint-*" ]; then
            for file in ${{ steps.changed-files.outputs.changed_files }}; do
              if ! [[ "$file" =~ \.github.* || "$file" =~ __test__ ]]; then
                if [[ "$file" =~ \.(js|jsx|ts|tsx|html)$ ]]; then
                  checkKeywords "$file"
                else
                  printf "File extension is not supported, linter will not analyze the file: $file \n\n"
                fi
              else
                printf "The file: $file belongs to an ignored folder, so the linter will skip it \n\n"
              fi
            done
            if [ "$total_warnings_collected" -gt 0 ]; then
              printf "$total_warnings_collected warning founds"
              exit 1
            fi
          else
            printf "Encountered restricted branch name, linter will not execute \n"
          fi
